{% set version = "1.0.4" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-modeltime.ensemble
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/modeltime.ensemble_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/modeltime.ensemble/modeltime.ensemble_{{ version }}.tar.gz
  sha256: 97245526db81ed7d7f877e3b42af4ad9edb2e2ca9c955eb469236f7229b9c288

build:
  merge_build_host: true  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-cli
    - r-doparallel
    - r-dplyr >=1.0.0
    - r-foreach
    - r-generics
    - r-glue
    - r-magrittr
    - r-modeltime >=1.2.3
    - r-modeltime.resample >=0.2.1
    - r-parsnip >=0.1.6
    - r-purrr
    - r-recipes >=0.1.15
    - r-rlang >=0.1.2
    - r-rsample
    - r-stringr
    - r-tibble
    - r-tictoc
    - r-tidyr
    - r-timetk >=2.5.0
    - r-tune >=0.1.2
    - r-workflows >=0.2.1
    - r-yardstick
  run:
    - r-base
    - r-cli
    - r-doparallel
    - r-dplyr >=1.0.0
    - r-foreach
    - r-generics
    - r-glue
    - r-magrittr
    - r-modeltime >=1.2.3
    - r-modeltime.resample >=0.2.1
    - r-parsnip >=0.1.6
    - r-purrr
    - r-recipes >=0.1.15
    - r-rlang >=0.1.2
    - r-rsample
    - r-stringr
    - r-tibble
    - r-tictoc
    - r-tidyr
    - r-timetk >=2.5.0
    - r-tune >=0.1.2
    - r-workflows >=0.2.1
    - r-yardstick

test:
  commands:
    - $R -e "library('modeltime.ensemble')"           # [not win]
    - "\"%R%\" -e \"library('modeltime.ensemble')\""  # [win]

about:
  home: https://github.com/business-science/modeltime.ensemble
  license: MIT
  summary: A 'modeltime' extension that implements time series ensemble forecasting methods including model averaging, weighted averaging, and stacking. These techniques are popular methods to improve forecast accuracy and stability. Refer to papers such as "Machine-Learning Models for Sales Time Series Forecasting" Pavlyshenko,
    B.M. (2019) <doi:10.3390>.
  license_family: MIT
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/MIT'
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
